name: 发包
on:
  push:
    branch: master

jobs:
  public-package:
    runs-on: ubuntu-latest
    steps:
      - name: 检出
        uses: actions/checkout@master

      - name: 写 public key
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

      - name: 安装依赖
        run: yarn

      - name: 打包
        run: yarn build

      - name: 发布
        run: npm publish
